stages:
    - test
    - build

test:
    stage: test
    script:
        - npm install
        - npm install -g grunt
        - grunt install
        - cp config-example.json config.json
        - grunt build
    tags:
        - nodejs

master:
    stage: build
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/webgnomeclient
        - docker push gitlab.orr.noaa.gov:5002/webgnomeclient
    tags:
        - shell
        - build
    only:
        - master
develop:
    stage: build
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/webgnomeclient:develop
        - docker push gitlab.orr.noaa.gov:5002/webgnomeclient:develop
    tags:
        - shell
        - build
    only:
        - develop

production:
    stage: build
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/webgnomeclient:production
        - docker push gitlab.orr.noaa.gov:5002/webgnomeclient:production
    tags:
        - shell
        - build
    only:
        - production

